Implemented DoS security module
oslabs-beta/obsidian pull request #1
Opened 2021-06-19 22:36 UTC by pjmsullivan

Implemented Denial of Service attack security module enabling devs to set a maximum query nesting depth value, above which, queries will be rejected.

# Checklist

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

# Related Issue

Previously, Obsidian did not allow for instantiation of a GraphQL security strategy.  This feature easily allows for a developer-designated value to establish a maximum query depth limit to prevent a DoS attack of deeply-nested or recursive queries from overloading  the GraphQL runtime.  

# Solution

The solution was to provide a new DoSSecurity.ts module that allows developers to specify the maximum nested query depth upon initialization of the ObsidianRouter.  By default, the security feature is disabled with a value of 0.  If a value is specified, all GraphQL queries and mutations will be evaluated against the maximum query depth, and queries that exceed the maximum will not be routed to the GraphQL runtime, neutralizing a potential nested query DoS attack.

# Additional Info

This module was written in typescript.

2021-06-24 18:21 UTC, cssim22 commented on src/destructure.js
> +export default function destructureQueries(queryOperationStr) {
Agree with updated export default syntax

2021-06-24 18:23 UTC, cssim22 commented on src/obsidian.ts
> +    // console.log('inside if');
Remove this console log

2021-06-24 18:27 UTC, cssim22 approved these changes
All changes look great and are working as intended.

2021-06-24 19:27 UTC, cssim22 commented on test_files/rhum_test_files/DoSSecurity_test.ts
> +      const results = queryDepthLimiter(test.DEPTH_2_QUERY, 10);
should change depth test value to 2

2021-06-24 19:33 UTC, cssim22 requested changes
Create additional tests to confirm function of depth check with multiple queries/mutations at the same time.

2021-06-24 23:50 UTC, cssim22 approved these changes
All changes have been reviewed and tested.

2021-06-28 18:35 UTC, justinwmckay approved these changes
Love it.

2021-06-28 18:40 UTC, cssim22 commented
Security measures reviewed and approved

2021-06-28 18:40 UTC, merged