newNormalize functionality
oslabs-beta/obsidian pull request #14
Opened 2020-12-14 17:46 UTC by ericmarc159

2020-12-15 18:03 UTC, dsymiller requested changes

2020-12-15 18:03 UTC, dsymiller commented on src/newNormalize.js
> +    const resultArray = resultObj.data[name];
We need logic for handling the case where the resultObject for a query is not an array but a single object.
resultObj = { 
data: {
actor: 
      {
        __typename: 'Actor',
        id: '1',
        firstName: 'Harrison',
        lastName: 'Ford',
   }
}
}

2020-12-16 15:52 UTC, EsmaShr approved these changes

2020-12-16 16:16 UTC, EsmaShr approved these changes

2020-12-16 16:18 UTC, merged