New destructure unit tests and updated test read_me
oslabs-beta/obsidian pull request #15
Opened 2020-12-14 20:48 UTC by tonstock

2020-12-15 16:19 UTC, dsymiller requested changes

2020-12-17 16:48 UTC, tonstock commented on test_files/rhum_test_files/destructure_test.ts
> +
We can, it just requires us to expose all of those functions and export them. 

Deno lacks a great package 'rewire' that helps with this.

2020-12-17 16:48 UTC, tonstock commented on test_files/rhum_test_files/destructure_test.ts
> +const ALL_ACTION_MOVIES = `
All of this is done. I just need to align with you on how to push it up. My commits are all out of whack.

2020-12-17 17:43 UTC, dsymiller submitted a review, later dismissed
Looks good

2020-12-17 21:23 UTC, lourentflores commented on test_files/rhum_test_files/destructure_test.ts
> +      Rhum.asserts.assertEquals(testResult, {});
the arguments for assert equal are the same, instead of comparing testResult to result

2020-12-17 21:24 UTC, lourentflores commented on test_files/rhum_test_files/destructure_test.ts
> +      Rhum.asserts.assertEquals(testResult, {});
the arguments for assert equal are the same, instead of comparing testResult to result

2020-12-17 21:26 UTC, dsymiller commented on test_files/rhum_test_files/destructure_test.ts
> +      Rhum.asserts.assertEquals(testResult, {});
lol

2020-12-17 21:27 UTC, dsymiller commented on test_files/rhum_test_files/destructure_test.ts
> +      Rhum.asserts.assertEquals(testResult, {});
this way we never have to fail tests.

2020-12-17 21:27 UTC, dsymiller commented on test_files/rhum_test_files/destructure_test.ts
> +      Rhum.asserts.assertEquals(testResult, {});
good catch

2020-12-31 13:32 UTC, lourentflores approved these changes

2020-12-31 15:42 UTC, dsymiller approved these changes

2020-12-31 15:42 UTC, merged