Update normalize
oslabs-beta/obsidian pull request #27
Opened 2020-12-22 01:32 UTC by ericmarc159

2020-12-22 16:13 UTC, dsymiller requested changes

2020-12-22 16:13 UTC, dsymiller commented on src/newNormalize.js
> +        //iterates thru the array of objects and stores the hash in the result object with 'DELETE' as value
all 'DELETE' should be 'DELETED'

2020-12-22 16:13 UTC, dsymiller commented on src/newNormalize.js
> +    deleteMovie: [
to match the above example this shouldn't be an array

2020-12-22 16:13 UTC, dsymiller commented on src/newNormalize.js
> +  ROOT_MUTATION: { 'deleteMovie(id:4)': ['Movie~4'] },
to match above example this shouldn't be an Array

2020-12-22 16:13 UTC, dsymiller commented on src/newNormalize.js
> +  if (deleteFlag) {
How does normalize handle mutations when the delete flag is not set to true? I'm not seeing functionality for that.

2020-12-22 18:24 UTC, dsymiller commented on src/newNormalize.js
> -  const query = queryObj.queries;
do we still need this new name funcitonality?

2020-12-27 13:40 UTC, dsymiller approved these changes
Looks good!

2020-12-27 20:52 UTC, EsmaShr approved these changes

2020-12-30 15:23 UTC, merged